const cloud = require('wx-server-sdk');
cloud.init({ env: cloud.DYNAMIC_CURRENT_ENV });
const db = cloud.database();
const _ = db.command;
const auth = require('../../common/auth');
const permission = require('../../common/permission');
const { success, fail } = require('../../common/response');
const { validateTaskTitle, validatePriority, validateScheduleType, validateObjectId } = require('../../common/validator');
const { SCHEDULE_TYPE, TASK_STATUS } = require('../../common/constants');
const { writeActivityLog } = require('../../common/logger');
const { recalculateProjectProgress } = require('../../common/project-progress');

async function ownedProject(openid, projectId) { const r = await db.collection('projects').doc(projectId).get().catch(() => ({ data: null })); return r.data && !r.data.deletedAt && permission.canEditProject(openid, r.data) ? r.data : null; }
async function rawOwnedProject(openid, projectId) { const r = await db.collection('projects').doc(projectId).get().catch(() => ({ data: null })); return r.data && permission.canReadProject(openid, r.data) ? r.data : null; }
function input(payload) {
  const title = validateTaskTitle(payload.title); if (!title.valid) return { error: title.message };
  if (payload.note !== undefined && typeof payload.note !== 'string') return { error: '备注格式无效' };
  if (typeof payload.note === 'string' && payload.note.trim().length > 500) return { error: '备注不能超过500字' };
  const priority = validatePriority(payload.priority || 'important'); if (!priority.valid) return { error: priority.message };
  const scheduleType = validateScheduleType(payload.scheduleType || SCHEDULE_TYPE.NONE); if (!scheduleType.valid) return { error: scheduleType.message };
  const startAt = payload.startAt ? new Date(payload.startAt) : null, endAt = payload.endAt ? new Date(payload.endAt) : null, dueAt = payload.dueAt ? new Date(payload.dueAt) : null;
  if (scheduleType.value === SCHEDULE_TYPE.DEADLINE && !isValidDate(dueAt)) return { error: '请设置有效的截止时间', code: 'INVALID_TIME_RANGE' };
  if (scheduleType.value === SCHEDULE_TYPE.RANGE && (!isValidDate(startAt) || !isValidDate(endAt) || endAt < startAt)) return { error: '请正确设置起止时间', code: 'INVALID_TIME_RANGE' };
  return { data: { title: title.value, note: typeof payload.note === 'string' ? payload.note.trim().slice(0, 500) : '', priority: priority.value, scheduleType: scheduleType.value, startAt: scheduleType.value === SCHEDULE_TYPE.RANGE ? startAt : null, endAt: scheduleType.value === SCHEDULE_TYPE.RANGE ? endAt : null, dueAt: scheduleType.value === SCHEDULE_TYPE.DEADLINE ? dueAt : null, groupId: typeof payload.groupId === 'string' && payload.groupId ? payload.groupId : null } };
}
function isValidDate(value) { return value instanceof Date && !Number.isNaN(value.getTime()); }
async function verifyGroup(projectId, groupId) { if (!groupId) return true; const r = await db.collection('project_groups').doc(groupId).get().catch(() => ({ data: null })); return !!(r.data && !r.data.deletedAt && r.data.projectId === projectId); }
async function cancelPendingReminders(taskId) { try { await db.collection('reminders').where({ taskId, status: 'pending' }).update({ data: { status: 'cancelled', updatedAt: db.serverDate() } }); } catch (error) { console.error('[task] cancel reminders failed:', taskId, error); } }
async function create(payload, context) {
  const openid = auth.getUserId(context); const projectId = validateObjectId(payload.projectId); const parsed = input(payload);
  if (!openid) return fail('UNAUTHORIZED', '无法获取用户身份'); if (!projectId.valid || parsed.error) return fail(parsed.code || 'INVALID_PARAMS', projectId.valid ? parsed.error : projectId.message);
  const project = await ownedProject(openid, projectId.value); if (!project) return fail('PROJECT_NOT_FOUND', '事件不存在或无权操作');
  if (project.status !== 'active') return fail('FORBIDDEN', '只有进行中的事件才能添加任务'); if (!await verifyGroup(project._id, parsed.data.groupId)) return fail('GROUP_NOT_FOUND', '分组不存在');
  const last = await db.collection('tasks').where({ projectId: project._id, groupId: parsed.data.groupId, deletedAt: null }).orderBy('sortOrder', 'desc').limit(1).get();
  const doc = { ...parsed.data, projectId: project._id, ownerId: openid, creatorId: openid, assigneeId: openid, teamId: null, sourceType: 'personal', approvalRequired: false, parentTaskId: null, level: 1, pathIds: [], status: TASK_STATUS.TODO, completedAt: null, completedBy: null, statusBeforeParentClose: null, deletedAt: null, sortOrder: last.data.length ? last.data[0].sortOrder + 1000 : 1000, createdAt: db.serverDate(), updatedAt: db.serverDate() };
  const result = await db.collection('tasks').add({ data: doc }); const progress = await recalculateProjectProgress(project._id);
  await writeActivityLog({ projectId: project._id, taskId: result._id, operatorId: openid, action: 'task.created', targetType: 'task', targetId: result._id, targetTitleSnapshot: doc.title, after: parsed.data, visibleTo: [openid] });
  return success({ task: { ...doc, _id: result._id }, progress }, '任务已创建');
}
async function listByProject(payload, context) { const openid = auth.getUserId(context); const id = validateObjectId(payload.projectId); if (!openid) return fail('UNAUTHORIZED', '无法获取用户身份'); if (!id.valid) return fail('INVALID_PARAMS', id.message); const project = await ownedProject(openid, id.value); if (!project) return fail('PROJECT_NOT_FOUND', '事件不存在或无权访问'); const r = await db.collection('tasks').where({ projectId: project._id, deletedAt: null }).orderBy('sortOrder', 'asc').limit(100).get(); return success({ tasks: r.data }); }
async function listDeleted(payload, context) { const openid = auth.getUserId(context); if (!openid) return fail('UNAUTHORIZED', '无法获取用户身份'); const r = await db.collection('tasks').where({ ownerId: openid, deletedAt: _.neq(null) }).orderBy('updatedAt', 'desc').limit(100).get(); const projectIds = [...new Set(r.data.map(item => item.projectId))]; const projects = await Promise.all(projectIds.map(id => rawOwnedProject(openid, id))); const map = {}; projects.filter(Boolean).forEach(item => { map[item._id] = item; }); return success({ tasks: r.data.map(item => ({ ...item, projectTitle: map[item.projectId] ? map[item.projectId].title : '原事件不存在', parentProjectDeleted: !!(map[item.projectId] && map[item.projectId].deletedAt) })) }); }
async function get(payload, context) { const openid = auth.getUserId(context); const id = validateObjectId(payload.taskId); if (!openid) return fail('UNAUTHORIZED', '无法获取用户身份'); if (!id.valid) return fail('INVALID_PARAMS', id.message); const r = await db.collection('tasks').doc(id.value).get().catch(() => ({ data: null })); const task = r.data; const project = task && await ownedProject(openid, task.projectId); return task && project && !task.deletedAt ? success({ task }) : fail('NOT_FOUND', '任务不存在或无权访问'); }
async function update(payload, context) { const openid = auth.getUserId(context); const id = validateObjectId(payload.taskId); const parsed = input(payload); if (!openid) return fail('UNAUTHORIZED', '无法获取用户身份'); if (!id.valid || parsed.error) return fail(parsed.code || 'INVALID_PARAMS', id.valid ? parsed.error : id.message); const r = await db.collection('tasks').doc(id.value).get().catch(() => ({ data: null })); const task = r.data; if (!task || task.deletedAt) return fail('TASK_NOT_FOUND', '任务不存在'); const project = await ownedProject(openid, task.projectId); if (!project) return fail('FORBIDDEN', '无权修改该任务');
  if (project.status !== 'active') return fail('FORBIDDEN', '只有进行中的事件才能修改任务'); if (!await verifyGroup(project._id, parsed.data.groupId)) return fail('GROUP_NOT_FOUND', '分组不存在'); await db.collection('tasks').doc(task._id).update({ data: { ...parsed.data, updatedAt: db.serverDate() } }); if (task.scheduleType !== parsed.data.scheduleType || String(task.startAt || '') !== String(parsed.data.startAt || '') || String(task.endAt || '') !== String(parsed.data.endAt || '') || String(task.dueAt || '') !== String(parsed.data.dueAt || '')) await cancelPendingReminders(task._id); const progress = await recalculateProjectProgress(project._id); await writeActivityLog({ projectId: project._id, taskId: task._id, operatorId: openid, action: 'task.updated', targetType: 'task', targetId: task._id, targetTitleSnapshot: parsed.data.title, before: { title: task.title, groupId: task.groupId, priority: task.priority, scheduleType: task.scheduleType, startAt: task.startAt, endAt: task.endAt, dueAt: task.dueAt }, after: parsed.data, visibleTo: [openid] }); return success({ progress }, '任务已更新'); }
async function toggle(payload, context, completed) { const openid = auth.getUserId(context); const id = validateObjectId(payload.taskId); if (!openid) return fail('UNAUTHORIZED', '无法获取用户身份'); if (!id.valid) return fail('INVALID_PARAMS', id.message); const r = await db.collection('tasks').doc(id.value).get().catch(() => ({ data: null })); const task = r.data; if (!task || task.deletedAt) return fail('TASK_NOT_FOUND', '任务不存在'); const project = await ownedProject(openid, task.projectId); if (!project) return fail('FORBIDDEN', '无权操作该任务');
  if (project.status !== 'active') return fail('FORBIDDEN', '只有进行中的事件才能操作任务'); const expected = completed ? TASK_STATUS.TODO : TASK_STATUS.COMPLETED, target = completed ? TASK_STATUS.COMPLETED : TASK_STATUS.TODO; if (task.status === target) return success({ progress: await recalculateProjectProgress(project._id) }, completed ? '任务已完成' : '任务已是未完成状态'); if (task.status !== expected) return fail('VERSION_CONFLICT', '任务状态已变化，请刷新后重试'); const after = completed ? { status: target, completedAt: db.serverDate(), completedBy: openid, updatedAt: db.serverDate() } : { status: target, completedAt: null, completedBy: null, updatedAt: db.serverDate() }; const changed = await db.collection('tasks').where({ _id: task._id, status: expected, deletedAt: null }).update({ data: after }); if (!changed.stats.updated) return success({ progress: await recalculateProjectProgress(project._id) }, '任务状态已更新'); if (completed) await cancelPendingReminders(task._id); const progress = await recalculateProjectProgress(project._id); await writeActivityLog({ projectId: project._id, taskId: task._id, operatorId: openid, action: completed ? 'task.completed' : 'task.reopened', targetType: 'task', targetId: task._id, targetTitleSnapshot: task.title, before: { status: expected }, after: { status: target }, visibleTo: [openid] }); return success({ progress }, completed ? '任务已完成' : '任务已重新打开'); }
async function complete(payload, context) { return toggle(payload, context, true); } async function reopen(payload, context) { return toggle(payload, context, false); }
async function softDelete(payload, context) { const openid = auth.getUserId(context); const id = validateObjectId(payload.taskId); if (!openid) return fail('UNAUTHORIZED', '无法获取用户身份'); if (!id.valid) return fail('INVALID_PARAMS', id.message); const r = await db.collection('tasks').doc(id.value).get().catch(() => ({ data: null })); const task = r.data; if (!task || task.deletedAt) return fail('TASK_NOT_FOUND', '任务不存在'); const project = await ownedProject(openid, task.projectId); if (!project) return fail('FORBIDDEN', '无权删除该任务');
  if (project.status !== 'active') return fail('FORBIDDEN', '只有进行中的事件才能删除任务'); await db.collection('tasks').doc(task._id).update({ data: { deletedAt: db.serverDate(), updatedAt: db.serverDate() } }); await cancelPendingReminders(task._id); const progress = await recalculateProjectProgress(project._id); await writeActivityLog({ projectId: project._id, taskId: task._id, operatorId: openid, action: 'task.deleted', targetType: 'task', targetId: task._id, targetTitleSnapshot: task.title, before: { deletedAt: null }, after: { deletedAt: 'serverDate' }, visibleTo: [openid] }); return success({ progress }, '任务已移入回收站'); }
async function restore(payload, context) { const openid = auth.getUserId(context); const id = validateObjectId(payload.taskId); if (!openid) return fail('UNAUTHORIZED', '无法获取用户身份'); if (!id.valid) return fail('INVALID_PARAMS', id.message); const r = await db.collection('tasks').doc(id.value).get().catch(() => ({ data: null })); const task = r.data; if (!task || !task.deletedAt) return fail('TASK_NOT_FOUND', '回收站中未找到任务'); const project = await rawOwnedProject(openid, task.projectId); if (!project) return fail('FORBIDDEN', '无权恢复该任务'); if (project.deletedAt) return fail('TASK_PARENT_PROJECT_DELETED', '请先恢复所属事件'); let groupId = task.groupId; if (groupId && !await verifyGroup(project._id, groupId)) groupId = null; await db.collection('tasks').doc(task._id).update({ data: { deletedAt: null, groupId, updatedAt: db.serverDate() } }); const progress = await recalculateProjectProgress(project._id); await writeActivityLog({ projectId: project._id, taskId: task._id, operatorId: openid, action: 'task.restored', targetType: 'task', targetId: task._id, targetTitleSnapshot: task.title, before: { deletedAt: task.deletedAt, groupId: task.groupId }, after: { deletedAt: null, groupId }, visibleTo: [openid] }); return success({ progress }, '任务已恢复'); }
async function reorder(payload, context) { const openid = auth.getUserId(context); const id = validateObjectId(payload.projectId); const taskIds = Array.isArray(payload.taskIds) ? payload.taskIds : []; if (!openid) return fail('UNAUTHORIZED', '无法获取用户身份'); if (!id.valid) return fail('INVALID_PARAMS', id.message); const project = await ownedProject(openid, id.value); if (!project) return fail('PROJECT_NOT_FOUND', '事件不存在或无权操作');
  if (project.status !== 'active') return fail('FORBIDDEN', '只有进行中的事件才能排序任务'); if (!taskIds.length || new Set(taskIds).size !== taskIds.length) return fail('INVALID_REORDER', '任务排序数据无效'); const rows = await Promise.all(taskIds.map(taskId => db.collection('tasks').doc(taskId).get().catch(() => ({ data: null })))); const tasks = rows.map(row => row.data); if (tasks.some(task => !task || task.deletedAt || task.projectId !== project._id)) return fail('INVALID_REORDER', '排序中包含无效任务'); const groupId = tasks[0].groupId || null; if (tasks.some(task => (task.groupId || null) !== groupId)) return fail('INVALID_REORDER', '只能在同一分组内排序'); const expected = await db.collection('tasks').where({ projectId: project._id, groupId, deletedAt: null }).get(); const expectedIds = expected.data.map(item => item._id).sort(), receivedIds = [...taskIds].sort(); if (expectedIds.length !== receivedIds.length || expectedIds.some((value, index) => value !== receivedIds[index])) return fail('VERSION_CONFLICT', '任务列表已变化，请刷新后重试'); await Promise.all(taskIds.map((taskId, i) => db.collection('tasks').doc(taskId).update({ data: { sortOrder: (i + 1) * 1000, updatedAt: db.serverDate() } }))); await writeActivityLog({ projectId: project._id, taskId: taskIds[0], operatorId: openid, action: 'task.reordered', targetType: 'task', targetTitleSnapshot: '任务排序', after: { groupId, taskIds }, visibleTo: [openid] }); return success(null, '任务排序已保存'); }
module.exports = { create, listByProject, listDeleted, get, update, complete, reopen, softDelete, restore, reorder };
